esphome:
  name: "6-pack-pin"
  friendly_name: 6 Pack pin

external_components:
  - source:
      type: git
      url: https://github.com/tongdaihg/test

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: "2.4nvc"
  password: "112233888"
  ap:
    ssid: "Seplos_NVC"
    password: "12345678"
  power_save_mode: none
  reboot_timeout: 0s

captive_portal:

ota:
  platform: esphome

logger:
  level: DEBUG

web_server:
  port: 80

uart:
  - id: seplos
    tx_pin: GPIO22
    rx_pin: GPIO21
    baud_rate: 19200
    rx_buffer_size: 2048

substitutions:
  time: "5"  # update interval for all data points (seconds)

seplos_parser:
  id: seplos_v3
  bms_count: 6
  update_interval: ${time}
  uart_id: seplos

sensor:
 # bms0
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 pack_voltage
    unit_of_measurement: "V"
    accuracy_decimals: 2
    filters:
      - throttle: ${time}s

text_sensor:
 # bms0
  - platform: seplos_parser
    seplos_parser_id: seplos_v3
    name: bms0 system_status